### ISSUE TITLE
write script to detect deletions

### ISSUE THREAD

**Issue by vict0rsch** [cc-ai/floods-gans#3]
from a googleimagesdownload output, write a small script which compares directory to logs to detect deleted photos and consequently deletes them in other folders

**Comment by bsahil29** [comment]
Attached is the link to script which compares image directory and logs to detect the deletions and consequently update the log file :  [metadata_script.py](https://github.com/cc-ai/floods-gans/blob/master/various_scripts/metadata_script.py)
